var user_image = document.getElementById("user-image");
var modal = document.getElementById("logout-modal");
window.onclick = function(event) { // Al click su ogni parte della pagina...
    if (event.target == user_image) { // .. se l'utente clicca proprio sulla user_image...
        if(modal.style.display == ""){ // .. e se il valore dela proprietà 'display' della finestra di logout è "none"...
            modal.style.display = "block"; // .. appare la finestra di logout
        }else{
             modal.style.display = ""; // , altrimenti sparisce la finestra.
            }
    }else{ // Se l'utente clicca in qualsiasi altri punto della pagina...
        if(modal.style.display == "block"){ // e solo se la finestra di logout è visibile...
            modal.style.display = ""; // la finestra sparisce.
        }
    }
}